FROM python:3.9

WORKDIR /app

ADD . /app

RUN apt-get update && apt-get -y upgrade

RUN pip3 install --upgrade pip && pip3 install -r requirements.txt

ENTRYPOINT ["python3", "scheduler_main.py", "-c", "config.conf"]
